stages:
  - install
  - build
  - test
  - formatting

image: $CI_REGISTRY_IMAGE:latest

core_build:
  stage: build
  tags:
    - docker
  before_script:
    - cd DropMe
    - dotnet workload restore
  script:
    - dotnet build

desktop_build:
  stage: build
  tags:
    - docker
  before_script:
    - cd DropMe.Desktop
    - dotnet workload restore
  script:
    - dotnet build

android_build:
  stage: build
  tags:
    - docker
  before_script:
    - cd DropMe.Android
    - dotnet workload restore
  script:
    - dotnet build

core_test:
  stage: test
  tags:
    - docker
  before_script:
    - cd tests/DropMe.Tests
    - dotnet workload restore
  script:
    - dotnet test

core_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd DropMe
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

android_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd DropMe.Android
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

desktop_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd DropMe.Desktop
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

core_test_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd tests/DropMe.Tests
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes
  
pkgbuild_install:
  stage: install
  image: archlinux:base-devel
  tags:
    - docker
  before_script:
    - pacman -Syu git --noconfirm
    - useradd -m -s /bin/bash build
    - passwd -l build
    - 'git config --system http."https://gitlab.scss.tcd.ie/".extraheader "PRIVATE-TOKEN: ${CI_JOB_TOKEN}"''
    - "echo 'build ALL=(root) NOPASSWD: /usr/bin/pacman' > /etc/sudoers.d/build-pacman"
    - chmod 0440 /etc/sudoers.d/build-pacman
  script:
    - runuser -u build -- env GIT_ASKPASS=/bin/echo makepkg -si --noconfirm
  allow_failure: true
