stages:
  - deploy
  - build
  - test
  - formatting
  - install

image: $CI_REGISTRY_IMAGE:v2

core_build:
  stage: build
  tags:
    - docker
  before_script:
    - cd DropMe
    - dotnet workload restore
  script:
    - dotnet build -c Debug

desktop_build:
  stage: build
  tags:
    - docker
  before_script:
    - cd DropMe.Desktop
    - dotnet workload restore
  script:
    - dotnet build -c Debug

android_build:
  stage: build
  tags:
    - docker
  before_script:
    - cd DropMe.Android
    - dotnet workload restore
  script:
    - dotnet build -c Debug

core_test:
  stage: test
  tags:
    - docker
  before_script:
    - cd tests/DropMe.Tests
    - dotnet workload restore
  script:
    - dotnet test

core_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd DropMe
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

android_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd DropMe.Android
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

desktop_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd DropMe.Desktop
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

core_test_formatting:
  stage: formatting
  tags:
    - docker
  before_script:
    - cd tests/DropMe.Tests
    - dotnet workload restore
  script:
    - dotnet format --verify-no-changes

deploy_to_github:
  stage: deploy
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  variables:
    GIT_SSH_COMMAND: "ssh -i $GH_DEPLOY_KEY -o StrictHostKeyChecking=no -p 443 -o Hostname=ssh.github.com"
  before_script:
    - chmod 400 $GH_DEPLOY_KEY
  script:
    - git remote add github git@github.com:cchristinechan/DropMe.git
    - git fetch --unshallow
    - git push github HEAD:main
 
pkgbuild_install:
  stage: install
  image: archlinux:base-devel
  tags:
    - docker
  before_script:
    - pacman -Syu git --noconfirm
    - useradd -m -s /bin/bash build
    - passwd -l build
    - cd linux/arch
    - runuser -u build -- sed -i "s|git+https://gitlab.scss.tcd.ie|git+https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.scss.tcd.ie|g" PKGBUILD
    - "echo 'build ALL=(root) NOPASSWD: /usr/bin/pacman' > /etc/sudoers.d/build-pacman"
    - chmod 0440 /etc/sudoers.d/build-pacman
  script:
    - runuser -u build -- env GIT_ASKPASS=/bin/echo makepkg -si --noconfirm
  allow_failure: true